name: CI-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      REGISTRY: hkccr.ccs.tencentyun.com/abriko
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build . -t hkccr.ccs.tencentyun.com/chaosimpact/telegram-notion
          docker push hkccr.ccs.tencentyun.com/chaosimpact/telegram-notion

